version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - mysql
      - queue-worker
    command: "php artisan serve --host=0.0.0.0 --port=8000"

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
        - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: log_project
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
    volumes:
        - db_data:/var/lib/mysql

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-queue-worker
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    command: sh -c "until nc -z mysql 3306; do echo waiting for mysql; sleep 1; done; php artisan queue:work"

volumes:
  db_data:
